name: jane_solution
description: AOP website - promote better posture and feeling good from head to toes

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  animate_do: ^2.1.0
  cached_network_image: ^3.2.0
  cupertino_icons: ^1.0.2
  currency_text_input_formatter: ^2.1.5
  flutter_custom_clippers: ^2.0.0
  flutter_easyloading: ^3.0.5
  flutter_expanded_tile: ^0.3.6
  flutter_spinkit: ^5.0.0
  flutter_staggered_grid_view: ^0.6.2
  flutter_svg: ^1.0.3
  fluttertoast: ^8.0.9
  google_fonts: ^3.0.1
  hovering: ^1.0.4
  http: ^0.13.4
  provider: ^6.0.3
  shared_preferences: ^2.0.15
  shimmer: ^2.0.0
  sizer: ^2.0.15
  url_launcher: ^6.1.6
  webviewx: ^0.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.10.0

  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/images/

  fonts:
    - family: Avenir
      fonts:
        - asset: assets/fonts/Avenir-Light.ttf
